### ISSUE TITLE
Support multiple schema loading policies

### ISSUE THREAD

**Issue by tmnd1991** [agile-lab-dev/darwin#12]
As of 35eff558baedb675c6a4e870d3e732e69b63a416 we have only one loading policy of Avro schemas.

It is ok for a batch job to load initially the repository content and then keep it for the application lifetime, but for instance this is not feasible for a long running application such as a streaming job.

**Comment by SpyQuel** [comment]
Introduced a reload method on the `AvroSchemaManager` object that can be used to reload all the schemas from the chosen storage.
