### ISSUE TITLE
Isolated AvroSchemaManager and Connector as a dependency

### ISSUE THREAD

**Issue by davideicardi** [agile-lab-dev/darwin#20]
Some general considerations, let me know what do you think:

1. each instance of `AvroSchemaManager` class should be isolated and should not rely on the static `_cache` field. For example if I create two instances of `AvroSchemaManager` they should be isolated, while now share the same cache.

2. `Connector` should be a dependency of the `AvroSchemaManager` class, now it is automatically created using the `ServiceLoader`.

3. If a static cache is needed (for spark?) it should be just an instance of the `AvroSchemaManager`. The only static field should be `_instance`.

4. Why using `AtomicReference` with an immutable cache class instead of a mutable `ConcurrentHashMap`? I expect similar performance when reading and a simpler code. I'm wrong?

These changes in my opinion improve testability and extensibility of the library. Now it is difficult to use Darwin inside an unit test from an external app.

For example consider the tests inside `ApplicationSuite.scala`, all the tests rely on a global state, while each test should be isolated from the other.

Here a prototype branch with these changes: https://github.com/davideicardi/darwin

**Comment by SpyQuel** [comment]
Managers can now be created using the factory or directly instantiated passing a connector.
The factory now behaves like a real factory: an instance is maintained for each configuration provided.
