### ISSUE TITLE
Provide a way to inject HBase connection

### ISSUE THREAD

**Issue by davideicardi** [agile-lab-dev/darwin#21]
Each HBase connection is very expensive in term of resources.

From an application can be useful to reuse an existing HBase connection, so that only one connection is maintained. Maybe the hbase connector can create a new connection only if not provided.

This is probably related to #20, because we need a way "customize" the connector instance.

**Comment by tmnd1991** [comment]
Since the connection is opened only at the start of the application, I think that is not such waste of resources and time. The implications of this would be very big the in the design of the library imho.

**Comment by davideicardi** [comment]
For sure this is not urgent, but in my opinion is important to allow to specify the connectors:

- testability (in test we can mock the connector)
- isolation (use of different connectors for different use cases in the same app)
- less resources needed
- reuse of existing configuration (less overall configuration)
- ability to specify different options not currently available

Consider that I don't intend to change the actual behaviour, we just need an additional way to create the connectors.

**Comment by tmnd1991** [comment]
@SpyQuel Isn't that possible since 1.0.6?
