### ISSUE TITLE
Find methods by name and namespace

### ISSUE THREAD

**Issue by SpyQuel** [agile-lab-dev/darwin#33]
Decide if it makes sense to have methods that performs find on Schemas using their name (and namespace) to query the storage. The resulting Schemas will have an associated version (or timestamp).

**Comment by tmnd1991** [comment]
Isn't possible to just perform a `it.agilelab.darwin.manager.AvroSchemaManager#getAll` and then perform.

**Comment by SpyQuel** [comment]
You are right, the only thing that is missing is the version: if we have multiple schemas for the same entity (after one or more evolutions) how can we know which one is the latest?

**Comment by tmnd1991** [comment]
I would open another issue to add the version of the schema, what do you think?

**Comment by SpyQuel** [comment]
Yes I think that would be perfect
