### ISSUE TITLE
[Java8 only] Fix exception everytime AvroSchemaManagerFactory.getInstance is called

### ISSUE THREAD

**Issue by pietrobrunetti** [agile-lab-dev/darwin#52]
The Java8 related implementation for DarwinConcurrentHashMap **getOrElse** is broken due to an eager evaluation of the lazy (call-by-name) **default** input value by the inner java concurrent hashmap when delegating.

**Comment by tmnd1991** [comment]
Do you think you can work on it?

**Comment by pietrobrunetti** [comment]
> Do you think you can work on it?

Sure
