### ISSUE TITLE
Confluent Rest Connector

### ISSUE THREAD

**Issue by andr3a87** [agile-lab-dev/darwin#65]
# Scenario
Allow darwin to retrieve the schemes from confluent schema registry

# Problem statement
In some use cases or in products such as ChangeDataCapture, reference schema registry is Confluent.

# Proposed solution
- [ ] create new connector `ConfluentRestConnector` and use this api to retrieve schema 
```
http://localhost:8081/schemas/ids/:id
```

**Comment by tmnd1991** [comment]
This looks very interesting to me! (and I will probably need it soon)
How does it look, right now? Would you need some help to merge it?
