### ISSUE TITLE
AvroSingleObjectEncodingUtils getId wants unused ByteOrder

### ISSUE THREAD

**Issue by adarmiento** [agile-lab-dev/darwin#67]
`AvroSingleObjectEncodingUtils.schemaMap` is a `DarwinConcurrentHashMap.empty[Schema, (Long, Array[Byte])]`, however, the only method that accesses it only return the `Long` notation of the stored id. 

Moreover, the `AvroSingleObjectEncodingUtils.getId()` requires a `ByteOrder` object that is used to compute a byte array stored in the map and never retrieved (all other methods in this utility class recompute the byte array anyway), affecting readability (e.g. in `AvroSingleObjectEncodingUtils.generateAvroSingleObjectEncoded(stream, AvroSingleObjectEncodingUtils.getId(schema, endianness), endianness)` where `endianess` is repeated).

**Comment by tmnd1991** [comment]
Thx
